services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./code:/root/code


